const seed = [
  {id:1,name:'Арман С.',title:'Ремонт квартир под ключ',category:'Ремонт квартир',city:'Алматы',price:15000,rating:4.9,reviews:87,description:'Полный цикл работ: от демонтажа до чистовой отделки. Гарантия 2 года.',image:'https://images.unsplash.com/photo-1505798577917-a65157d3320a?auto=format&fit=crop&w=800&q=80',pro:true,phone:'+7 701 234 56 78'},
  {id:2,name:'Данияр К.',title:'Сантехник с выездом',category:'Сантехника',city:'Астана',price:7000,rating:4.8,reviews:64,description:'Устранение протечек, установка сантехники и отопления. Выезд в день обращения.',image:'https://images.unsplash.com/photo-1581244277943-fe4a9c777189?auto=format&fit=crop&w=800&q=80',pro:true,phone:'+7 702 555 21 10'},
  {id:3,name:'Сергей В.',title:'Электрик — любые работы',category:'Электрика',city:'Алматы',price:5000,rating:5,reviews:42,description:'Проводка, розетки, щитовые и поиск неисправностей. Работаю аккуратно.',image:'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=800&q=80',pro:false,phone:'+7 777 100 40 50'},
  {id:4,name:'Марат А.',title:'Сборка и ремонт мебели',category:'Мебель',city:'Шымкент',price:6000,rating:4.7,reviews:39,description:'Соберу шкаф, кухню или кровать. Ремонт механизмов и замена фурнитуры.',image:'https://images.unsplash.com/photo-1581783898377-1c85bf937427?auto=format&fit=crop&w=800&q=80',pro:false,phone:'+7 705 909 12 12'},
  {id:5,name:'Илья Н.',title:'Ремонт бытовой техники',category:'Техника',city:'Караганда',price:8000,rating:4.9,reviews:106,description:'Стиральные и посудомоечные машины, холодильники. Диагностика на дому.',image:'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',pro:true,phone:'+7 747 800 65 43'},
  {id:6,name:'Руслан Т.',title:'Автомеханик с выездом',category:'Авто',city:'Алматы',price:10000,rating:4.8,reviews:71,description:'Диагностика и мелкий ремонт автомобиля. Помогу подобрать запчасти.',image:'https://images.unsplash.com/photo-1632823469850-1b7b1e8b7e5e?auto=format&fit=crop&w=800&q=80',pro:false,phone:'+7 700 404 44 04'}
];

const read=(key,fallback=[])=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
let users=read('sheberUsers'), sessionId=localStorage.getItem('sheberSession'), currentUser=users.find(x=>x.id===sessionId)||null;
let activeCategory='Все', currentPage=1, favoritesOnly=false, pendingAction=null;
const userListings=()=>currentUser?read(`sheberListings_${currentUser.id}`):[];
const allListings=()=>[...users.flatMap(u=>read(`sheberListings_${u.id}`)),...seed];
const getFavorites=()=>new Set(currentUser?read(`sheberFavorites_${currentUser.id}`):[]);
const cards=document.querySelector('#cards'),empty=document.querySelector('#empty'),input=document.querySelector('#searchInput'),city=document.querySelector('#citySelect'),sort=document.querySelector('#sortSelect');
const authDialog=document.querySelector('#authDialog'),listingDialog=document.querySelector('#listingDialog');
const money=n=>new Intl.NumberFormat('ru-RU').format(n)+' ₸';
const normalize=s=>s.trim().toLowerCase();
const validIdentifier=s=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s)||/^\+?[\d\s()\-]{10,}$/.test(s);
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2600)}
function filtered(){const q=input.value.toLowerCase().trim(),favs=getFavorites();let data=allListings().filter(x=>(!favoritesOnly||favs.has(x.id))&&(activeCategory==='Все'||x.category===activeCategory)&&(city.value==='Все города'||x.city===city.value)&&(!q||`${x.title} ${x.description} ${x.category}`.toLowerCase().includes(q)));if(sort.value==='rating')data.sort((a,b)=>b.rating-a.rating);if(sort.value==='price')data.sort((a,b)=>a.price-b.price);if(sort.value==='popular')data.sort((a,b)=>b.reviews-a.reviews);return data}
function renderPagination(total){const pages=Math.ceil(total/6),nav=document.querySelector('#pagination');if(currentPage>pages)currentPage=Math.max(1,pages);if(pages<=1){nav.innerHTML='';return}nav.innerHTML=`<button class="page-arrow" data-page="${currentPage-1}" ${currentPage===1?'disabled':''} aria-label="Предыдущая страница">‹</button>${Array.from({length:pages},(_,i)=>`<button data-page="${i+1}" class="${currentPage===i+1?'active':''}">${i+1}</button>`).join('')}<button class="page-arrow" data-page="${currentPage+1}" ${currentPage===pages?'disabled':''} aria-label="Следующая страница">›</button>`}
function render(){const data=filtered(),favs=getFavorites(),pages=Math.ceil(data.length/6);if(currentPage>pages)currentPage=Math.max(1,pages);const start=(currentPage-1)*6;document.querySelector('#resultCount').textContent=`Найдено: ${data.length}`;cards.innerHTML=data.slice(start,start+6).map(x=>`<article class="card"><div class="card-img" data-open="${x.id}"><img src="${x.image||'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=800&q=80'}" alt="${x.title}" loading="lazy"><span class="badge">${x.pro?'✓ ПРОВЕРЕН':'НОВЫЙ МАСТЕР'}</span><button class="fav ${favs.has(x.id)?'saved':''}" data-fav="${x.id}" aria-label="В избранное">${favs.has(x.id)?'♥':'♡'}</button></div><div class="card-body"><div class="meta"><span>⌖ ${x.city}</span><span class="rating">★ ${x.rating} <i>(${x.reviews})</i></span></div><h3 data-open="${x.id}">${x.title}</h3><div class="person"><b>●</b> ${x.name}</div><p class="desc" data-open="${x.id}">${x.description}</p><div class="price-line"><strong>от ${money(x.price)}</strong><div class="card-actions"><button class="contact" data-phone="${x.phone}">Показать телефон</button>${currentUser&&x.ownerId===currentUser.id?`<button class="delete-listing" data-delete="${x.id}">Удалить</button>`:''}</div></div></div></article>`).join('');empty.style.display=data.length?'none':'block';empty.querySelector('b').textContent=favoritesOnly?'В избранном пока пусто':'Ничего не найдено';renderPagination(data.length)}
const detailsDialog=document.querySelector('#detailsDialog');
function openDetails(id){const x=allListings().find(item=>String(item.id)===String(id));if(!x)return;sessionStorage.setItem('sheberOpenListing',JSON.stringify(x));window.open(`listing.html?id=${encodeURIComponent(x.id)}`,'_blank')}
document.querySelector('.details-close').onclick=()=>detailsDialog.close();detailsDialog.onclick=e=>{if(e.target===detailsDialog)detailsDialog.close()};document.querySelector('#detailsPhone').onclick=e=>e.target.textContent=e.target.dataset.phone;
function updateHeader(){document.querySelector('#loginBtn').hidden=!!currentUser;document.querySelector('#accountBox').hidden=!currentUser;if(currentUser){document.querySelector('#accountName').textContent=currentUser.name;document.querySelector('#accountAvatar').textContent=currentUser.name.slice(0,1).toUpperCase()}render()}
function switchAuth(tab){document.querySelectorAll('[data-auth-tab]').forEach(b=>b.classList.toggle('active',b.dataset.authTab===tab));document.querySelector('#loginForm').hidden=tab!=='login';document.querySelector('#registerForm').hidden=tab!=='register';document.querySelector('#loginError').textContent='';document.querySelector('#registerError').textContent=''}
function openAuth(action=null,protectedAction=false){pendingAction=action;document.querySelector('#authMessage').hidden=!protectedAction;switchAuth('login');authDialog.showModal()}
function requireAuth(action){if(currentUser){action();return}openAuth(action,true)}
function completeAuth(message){authDialog.close();updateHeader();toast(message);const action=pendingAction;pendingAction=null;if(action)setTimeout(action,150)}
function fileToDataUrl(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error('Не удалось прочитать файл'));reader.readAsDataURL(file)})}

document.querySelectorAll('[data-auth-tab]').forEach(b=>b.onclick=()=>switchAuth(b.dataset.authTab));
document.querySelector('#loginBtn').onclick=()=>openAuth();document.querySelector('.auth-close').onclick=()=>{pendingAction=null;authDialog.close()};authDialog.onclick=e=>{if(e.target===authDialog){pendingAction=null;authDialog.close()}};
document.querySelector('#registerForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target)),error=document.querySelector('#registerError'),identifier=normalize(d.identifier);if(d.name.trim().length<2){error.textContent='Введите имя — минимум 2 символа';return}if(!validIdentifier(identifier)){error.textContent='Введите корректный email или номер телефона';return}if(d.password.length<6){error.textContent='Пароль должен содержать минимум 6 символов';return}if(d.password!==d.confirm){error.textContent='Пароли не совпадают';return}if(users.some(x=>x.identifier===identifier)){error.textContent='Пользователь с такими данными уже зарегистрирован';return}currentUser={id:'u'+Date.now(),name:d.name.trim(),identifier,password:d.password};users.push(currentUser);localStorage.setItem('sheberUsers',JSON.stringify(users));localStorage.setItem('sheberSession',currentUser.id);sessionId=currentUser.id;e.target.reset();completeAuth('Регистрация успешно завершена')};
document.querySelector('#loginForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target)),identifier=normalize(d.identifier),user=users.find(x=>x.identifier===identifier&&x.password===d.password);if(!user){document.querySelector('#loginError').textContent='Неверный телефон, email или пароль';return}currentUser=user;sessionId=user.id;localStorage.setItem('sheberSession',user.id);e.target.reset();completeAuth('Вы вошли в аккаунт')};
document.querySelector('#logoutBtn').onclick=()=>{currentUser=null;sessionId=null;favoritesOnly=false;localStorage.removeItem('sheberSession');updateHeader();toast('Вы вышли из аккаунта')};
document.querySelectorAll('.open-form').forEach(b=>b.onclick=()=>requireAuth(()=>listingDialog.showModal()));document.querySelector('.dialog-close').onclick=()=>listingDialog.close();listingDialog.onclick=e=>{if(e.target===listingDialog)listingDialog.close()};
const imageFile=document.querySelector('#imageFile'),imagePreview=document.querySelector('#imagePreview');
imageFile.onchange=()=>{const file=imageFile.files[0];imagePreview.hidden=true;if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)){toast('Выберите изображение JPG, PNG или WEBP');imageFile.value='';return}if(file.size>2*1024*1024){toast('Размер фотографии не должен превышать 2 МБ');imageFile.value='';return}imagePreview.src=URL.createObjectURL(file);imagePreview.hidden=false};
document.querySelector('#listingForm').onsubmit=async e=>{e.preventDefault();if(!currentUser)return openAuth(()=>listingDialog.showModal(),true);const form=e.target,file=imageFile.files[0],d=Object.fromEntries(new FormData(form));delete d.imageFile;try{if(file)d.image=await fileToDataUrl(file);const item={...d,id:Date.now(),ownerId:currentUser.id,name:d.name||currentUser.name,price:Number(d.price),rating:5,reviews:0,pro:false};const saved=userListings();saved.unshift(item);localStorage.setItem(`sheberListings_${currentUser.id}`,JSON.stringify(saved));listingDialog.close();form.reset();imagePreview.hidden=true;imagePreview.removeAttribute('src');favoritesOnly=false;activeCategory='Все';render();toast('Объявление опубликовано');document.querySelector('#catalog').scrollIntoView()}catch(error){toast(error.name==='QuotaExceededError'?'Недостаточно места. Выберите фото меньшего размера':'Не удалось сохранить фотографию')}};
document.querySelector('#favoritesBtn').onclick=()=>requireAuth(()=>{favoritesOnly=true;input.value='';city.value='Все города';activeCategory='Все';document.querySelectorAll('.category').forEach((x,i)=>x.classList.toggle('active',i===0));render();document.querySelector('#catalog').scrollIntoView()});
cards.onclick=e=>{const fav=e.target.closest('[data-fav]');if(fav){const id=Number(fav.dataset.fav);requireAuth(()=>{const set=getFavorites();set.has(id)?set.delete(id):set.add(id);localStorage.setItem(`sheberFavorites_${currentUser.id}`,JSON.stringify([...set]));render()});return}const del=e.target.closest('[data-delete]');if(del&&currentUser){const id=Number(del.dataset.delete);if(confirm('Удалить это объявление?')){const saved=userListings().filter(x=>x.id!==id);localStorage.setItem(`sheberListings_${currentUser.id}`,JSON.stringify(saved));render();toast('Объявление удалено')}return}const contact=e.target.closest('[data-phone]');if(contact){contact.textContent=contact.dataset.phone;return}const opener=e.target.closest('[data-open]');if(opener)openDetails(opener.dataset.open)};
document.querySelectorAll('.category').forEach(b=>b.onclick=()=>{document.querySelector('.category.active').classList.remove('active');b.classList.add('active');activeCategory=b.dataset.category;favoritesOnly=false;currentPage=1;render()});
document.querySelector('#searchForm').onsubmit=e=>{e.preventDefault();favoritesOnly=false;currentPage=1;render();document.querySelector('#catalog').scrollIntoView()};document.querySelectorAll('[data-query]').forEach(b=>b.onclick=()=>{input.value=b.dataset.query;favoritesOnly=false;currentPage=1;render();document.querySelector('#catalog').scrollIntoView()});[city,sort].forEach(el=>el.onchange=()=>{currentPage=1;render()});input.oninput=()=>{favoritesOnly=false;currentPage=1;render()};document.querySelector('#pagination').onclick=e=>{const button=e.target.closest('[data-page]');if(!button||button.disabled)return;currentPage=Number(button.dataset.page);render();document.querySelector('#catalog').scrollIntoView({behavior:'smooth'})};
updateHeader();
