const read=(key,fallback=[])=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
const money=n=>new Intl.NumberFormat('ru-RU').format(n)+' ₸';
const toast=message=>{const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2500)};
let user=null,listings=[],page=1,editingId=null,initialForm='';
const own=()=>listings.filter(item=>item.ownerId===user?.id);
const allListings=()=>[...listings,...(globalThis.SHEBER_LISTINGS||[])];
const favoriteKey=()=>`sheberFavorites_${user.id}`;

function updateIdentity(){
  document.querySelector('#profileAvatar').textContent=user.name.slice(0,1).toUpperCase();
  document.querySelector('#profileName').textContent=user.name;
  document.querySelector('#profileIdentifier').textContent=user.identifier;
  document.querySelector('#profileDate').textContent='На сайте с '+new Date(user.createdAt).toLocaleDateString('ru-RU',{day:'numeric',month:'long',year:'numeric'});
  document.querySelector('#settingsForm').elements.name.value=user.name;
  document.querySelector('#settingsForm').elements.identifier.value=user.identifier;
}
function card(x,owner=false){return `<article class="profile-card"><img src="${x.image||'логитип/логотип.png'}" alt="${x.title}"><div class="profile-card-content"><div class="profile-card-meta"><span>⌖ ${x.city}</span><span class="profile-status">● Активно</span></div><h3>${x.title}</h3><span class="profile-card-price">от ${money(x.price)}</span><div class="profile-card-meta"><span>${new Date(x.createdAt).toLocaleDateString('ru-RU')}</span><span>◉ ${x.views||0} просмотров</span></div><div class="profile-card-actions"><button class="card-open" data-open="${x.id}">Открыть</button>${owner?`<button class="card-edit" data-edit="${x.id}">Редактировать</button><button class="card-delete" data-delete="${x.id}">Удалить</button>`:''}</div></div></article>`}
function renderMine(){const data=own(),pages=Math.ceil(data.length/6);page=Math.min(page,Math.max(1,pages));document.querySelector('#mineCount').textContent=data.length;document.querySelector('#mineEmpty').hidden=!!data.length;document.querySelector('#mineGrid').innerHTML=data.slice((page-1)*6,page*6).map(x=>card(x,true)).join('');document.querySelector('#profilePagination').innerHTML=pages>1?Array.from({length:pages},(_,i)=>`<button data-page="${i+1}" class="${page===i+1?'active':''}">${i+1}</button>`).join(''):''}
function renderFavorites(){const ids=new Set(read(favoriteKey()).map(String)),data=allListings().filter(x=>ids.has(String(x.id)));document.querySelector('#favCount').textContent=data.length;document.querySelector('#favEmpty').hidden=!!data.length;document.querySelector('#favoritesGrid').innerHTML=data.map(x=>card(x)).join('')}
function openListing(id){const item=allListings().find(x=>String(x.id)===String(id));if(!item)return;sessionStorage.setItem('sheberOpenListing',JSON.stringify(item));location.href=`listing.html?id=${encodeURIComponent(id)}`}

document.querySelector('.profile-tabs').onclick=e=>{const b=e.target.closest('[data-tab]');if(!b)return;document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));['mine','favorites','settings'].forEach(n=>document.querySelector(`#${n}Panel`).hidden=n!==b.dataset.tab);if(b.dataset.tab==='favorites')renderFavorites()};
document.querySelector('#profilePagination').onclick=e=>{const b=e.target.closest('[data-page]');if(b){page=Number(b.dataset.page);renderMine()}};
document.querySelector('#profileLogout').onclick=async()=>{await Backend.logout();localStorage.removeItem('sheberSession');location.replace('index.html')};
document.querySelector('#settingsForm').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target)),error=document.querySelector('#settingsError');error.textContent='';if(d.name.trim().length<2)return error.textContent='Введите имя — минимум 2 символа';if(d.password&&d.password.length<6)return error.textContent='Пароль должен содержать минимум 6 символов';if(d.password!==d.confirm)return error.textContent='Пароли не совпадают';try{const updated=await Backend.updateAccount(d.name.trim(),d.password);user.name=updated.user_metadata?.name||d.name.trim();e.target.elements.password.value='';e.target.elements.confirm.value='';updateIdentity();toast('Профиль обновлён')}catch(err){error.textContent=err.message||'Не удалось обновить профиль'}};

const dialog=document.querySelector('#profileEditDialog'),form=document.querySelector('#profileEditForm'),file=document.querySelector('#profileEditFile'),preview=document.querySelector('#profileEditPreview');
const snapshot=()=>JSON.stringify({...Object.fromEntries(new FormData(form)),selectedFile:file.files[0]?[file.files[0].name,file.files[0].size]:null});
const toDataUrl=f=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(f)});
function openEdit(id){const item=own().find(x=>String(x.id)===String(id));if(!item)return toast('Нет прав для редактирования');editingId=item.id;['name','city','title','category','price','description','phone'].forEach(k=>form.elements[k].value=item[k]??'');form.elements.removePhoto.checked=false;file.value='';preview.src=item.image||'логитип/логотип.png';preview.hidden=false;initialForm=snapshot();dialog.showModal()}
function closeEdit(){if(snapshot()!==initialForm&&!confirm('Изменения не сохранены. Закрыть форму?'))return;dialog.close()}
document.querySelector('.profile-edit-close').onclick=closeEdit;document.querySelector('.cancel-profile-edit').onclick=closeEdit;dialog.addEventListener('cancel',e=>{e.preventDefault();closeEdit()});
file.onchange=()=>{const f=file.files[0];if(!f)return;if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>2*1024*1024){file.value='';return toast('Фото должно быть JPG, PNG или WEBP до 2 МБ')}preview.src=URL.createObjectURL(f);preview.hidden=false;form.elements.removePhoto.checked=false};form.elements.removePhoto.onchange=e=>preview.hidden=e.target.checked;
form.onsubmit=async e=>{e.preventDefault();const item=own().find(x=>String(x.id)===String(editingId));if(!item)return toast('Нет прав для изменения');const d=Object.fromEntries(new FormData(form));if(!/^\+?[\d\s()\-]{10,}$/.test(d.phone))return toast('Введите корректный номер телефона');delete d.imageFile;delete d.removePhoto;let image=form.elements.removePhoto.checked?'':item.image;try{if(file.files[0])image=await toDataUrl(file.files[0]);const updated=await Backend.updateListing(item.id,{...d,price:Number(d.price),image});listings=listings.map(x=>x.id===updated.id?updated:x);initialForm=snapshot();dialog.close();renderMine();toast('Изменения сохранены')}catch(err){toast(err.message||'Не удалось сохранить изменения')}};
document.querySelector('#mineGrid').onclick=async e=>{const open=e.target.closest('[data-open]'),edit=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]');if(open)return openListing(open.dataset.open);if(edit)return openEdit(edit.dataset.edit);if(del&&confirm('Вы действительно хотите удалить это объявление?'))try{await Backend.deleteListing(del.dataset.delete);listings=listings.filter(x=>String(x.id)!==del.dataset.delete);renderMine();toast('Объявление удалено')}catch{toast('Не удалось удалить объявление')}};
document.querySelector('#favoritesGrid').onclick=e=>{const open=e.target.closest('[data-open]');if(open)openListing(open.dataset.open)};

async function init(){try{const session=await Backend.session();if(!session)return location.replace('index.html?auth=1');const u=session.user;user={id:u.id,name:u.user_metadata?.name||u.email.split('@')[0],identifier:u.email,createdAt:u.created_at};listings=await Backend.listings();updateIdentity();renderMine();renderFavorites()}catch(err){toast('Не удалось загрузить личный кабинет')}}init();
