require('dotenv').config();
const express=require('express'),path=require('path'),crypto=require('crypto'),{DatabaseSync}=require('node:sqlite');
const app=express(),PORT=Number(process.env.PORT||3000),db=new DatabaseSync(path.join(__dirname,'stroy.db'));
app.disable('x-powered-by');app.use(express.json({limit:'4mb'}));
db.exec(`pragma journal_mode=WAL; pragma wal_autocheckpoint=1; pragma foreign_keys=ON;
create table if not exists users(id text primary key,name text not null,email text not null unique,password_hash text not null,created_at text not null);
create table if not exists sessions(token text primary key,user_id text not null references users(id) on delete cascade,created_at text not null);
create table if not exists listings(id text primary key,owner_id text not null references users(id) on delete cascade,name text not null,title text not null,category text not null,city text not null,price real not null,description text not null,phone text not null,image_url text,rating real not null default 5,reviews integer not null default 0,views integer not null default 0,status text not null default 'active',created_at text not null,updated_at text not null);
create table if not exists favorites(user_id text not null references users(id) on delete cascade,listing_id text not null references listings(id) on delete cascade,created_at text not null,primary key(user_id,listing_id));`);
const route=fn=>(req,res,next)=>Promise.resolve(fn(req,res,next)).catch(next),now=()=>new Date().toISOString();
const hash=password=>{const salt=crypto.randomBytes(16).toString('hex'),key=crypto.scryptSync(password,salt,64).toString('hex');return `${salt}:${key}`};
const verify=(password,stored)=>{const[salt,key]=stored.split(':'),actual=crypto.scryptSync(password,salt,64),expected=Buffer.from(key,'hex');return expected.length===actual.length&&crypto.timingSafeEqual(expected,actual)};
function currentUser(req){const token=req.headers.authorization?.replace(/^Bearer\s+/i,'');if(!token)return null;return db.prepare('select u.id,u.name,u.email,u.created_at from sessions s join users u on u.id=s.user_id where s.token=?').get(token)}
function requireUser(req,res){const user=currentUser(req);if(!user)res.status(401).json({message:'Войдите в аккаунт'});return user}
const publicUser=u=>({id:u.id,email:u.email,created_at:u.created_at,user_metadata:{name:u.name}});

app.get('/api/health',(req,res)=>res.json({status:'ok',database:'connected',engine:'sqlite',timestamp:now()}));
app.post('/api/auth/register',route(async(req,res)=>{const name=String(req.body.name||'').trim(),email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||'');if(name.length<2||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||password.length<6)return res.status(400).json({message:'Проверьте имя, email и пароль'});if(db.prepare('select id from users where email=?').get(email))return res.status(409).json({message:'Этот email уже зарегистрирован'});const user={id:crypto.randomUUID(),name,email,created_at:now()};db.prepare('insert into users(id,name,email,password_hash,created_at) values(?,?,?,?,?)').run(user.id,name,email,hash(password),user.created_at);const token=crypto.randomBytes(32).toString('hex');db.prepare('insert into sessions(token,user_id,created_at) values(?,?,?)').run(token,user.id,now());res.status(201).json({user:publicUser(user),session:{access_token:token,refresh_token:token}})}));
app.post('/api/auth/login',(req,res)=>{const email=String(req.body.email||'').trim().toLowerCase(),user=db.prepare('select * from users where email=?').get(email);if(!user||!verify(String(req.body.password||''),user.password_hash))return res.status(401).json({message:'Неверный email или пароль'});const token=crypto.randomBytes(32).toString('hex');db.prepare('insert into sessions(token,user_id,created_at) values(?,?,?)').run(token,user.id,now());res.json({user:publicUser(user),session:{access_token:token,refresh_token:token}})});
app.get('/api/auth/session',(req,res)=>{const user=requireUser(req,res);if(user)res.json({user:publicUser(user)})});
app.post('/api/auth/logout',(req,res)=>{const token=req.headers.authorization?.replace(/^Bearer\s+/i,'');if(token)db.prepare('delete from sessions where token=?').run(token);res.status(204).end()});

app.get('/api/listings',(req,res)=>res.json(db.prepare("select * from listings where status='active' order by created_at desc").all()));
app.get('/api/listings/:id',(req,res)=>{const item=db.prepare('select * from listings where id=?').get(req.params.id);item?res.json(item):res.status(404).json({message:'Объявление не найдено'})});
app.post('/api/listings',(req,res)=>{const user=requireUser(req,res);if(!user)return;const x=req.body,item={id:crypto.randomUUID(),owner_id:user.id,name:String(x.name||user.name),title:String(x.title||''),category:String(x.category||''),city:String(x.city||''),price:Number(x.price),description:String(x.description||''),phone:String(x.phone||''),image_url:x.image||null,created_at:now(),updated_at:now()};if(!item.title||!item.category||!item.city||!item.description||!item.phone||item.price<0)return res.status(400).json({message:'Заполните все поля объявления'});db.prepare('insert into listings(id,owner_id,name,title,category,city,price,description,phone,image_url,created_at,updated_at) values(@id,@owner_id,@name,@title,@category,@city,@price,@description,@phone,@image_url,@created_at,@updated_at)').run(item);res.status(201).json(db.prepare('select * from listings where id=?').get(item.id))});
app.patch('/api/listings/:id',(req,res)=>{const user=requireUser(req,res);if(!user)return;const old=db.prepare('select * from listings where id=? and owner_id=?').get(req.params.id,user.id);if(!old)return res.status(403).json({message:'Нет прав на редактирование'});const x=req.body;db.prepare('update listings set name=?,title=?,category=?,city=?,price=?,description=?,phone=?,image_url=?,updated_at=? where id=? and owner_id=?').run(x.name,x.title,x.category,x.city,Number(x.price),x.description,x.phone,x.image||null,now(),req.params.id,user.id);res.json(db.prepare('select * from listings where id=?').get(req.params.id))});
app.delete('/api/listings/:id',(req,res)=>{const user=requireUser(req,res);if(!user)return;db.prepare('delete from listings where id=? and owner_id=?').run(req.params.id,user.id);res.status(204).end()});

app.get('/api/profile',(req,res)=>{const user=requireUser(req,res);if(user)res.json({id:user.id,name:user.name,identifier:user.email,created_at:user.created_at})});
app.patch('/api/profile',(req,res)=>{const user=requireUser(req,res);if(!user)return;const name=String(req.body.name||'').trim(),password=String(req.body.password||'');if(name.length<2||password&&password.length<6)return res.status(400).json({message:'Проверьте имя и пароль'});if(password)db.prepare('update users set name=?,password_hash=? where id=?').run(name,hash(password),user.id);else db.prepare('update users set name=? where id=?').run(name,user.id);res.json({id:user.id,name,identifier:user.email})});
app.get('/api/favorites',(req,res)=>{const user=requireUser(req,res);if(!user)return;res.json(db.prepare('select f.listing_id,l.* from favorites f join listings l on l.id=f.listing_id where f.user_id=? order by f.created_at desc').all(user.id))});
app.post('/api/favorites/:id',(req,res)=>{const user=requireUser(req,res);if(!user)return;db.prepare('insert or ignore into favorites(user_id,listing_id,created_at) values(?,?,?)').run(user.id,req.params.id,now());res.status(201).json({listing_id:req.params.id})});
app.delete('/api/favorites/:id',(req,res)=>{const user=requireUser(req,res);if(!user)return;db.prepare('delete from favorites where user_id=? and listing_id=?').run(user.id,req.params.id);res.status(204).end()});

const frontend=path.resolve(__dirname,'..','frontend');app.use(express.static(frontend));app.get('/main',(req,res)=>res.sendFile(path.join(frontend,'index.html')));app.get('/cabinet',(req,res)=>res.sendFile(path.join(frontend,'profile.html')));app.get('/listing/:id',(req,res)=>res.sendFile(path.join(frontend,'listing.html')));app.use((req,res)=>res.status(404).sendFile(path.join(frontend,'index.html')));app.use((error,req,res,next)=>{console.error(error);res.status(500).json({message:'Внутренняя ошибка сервера'})});app.listen(PORT,'0.0.0.0',()=>console.log(`Stroy.kz: http://localhost:${PORT}`));
