name: Публикация на GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Получить файлы репозитория
        uses: actions/checkout@v4
      - name: Настроить GitHub Pages
        uses: actions/configure-pages@v5
      - name: Подготовить статические файлы
        uses: actions/upload-pages-artifact@v4
        with:
          path: frontend
      - name: Опубликовать сайт
        id: deployment
        uses: actions/deploy-pages@v4
